### PR TITLE
allow for shallow cloning of repositories

### PR DESCRIPTION
**Pull request by naesheim**
Would you be interested in allowing shallow clones?

### CODE REVIEW

**Comment by al-jeyapal** [comment]
Perhaps, we'll just do some testing prior to merge. Thanks for the contribution.

**Comment by al-jeyapal** [comment]
@naesheim, did you close this because you were withdrawing the request?

**Comment by naesheim** [comment]
I wanted to update it with '--no-single-branch'. I think this is a better solution. Especially considering your existing methods of checking out alternative branches.

**Comment by al-jeyapal** [comment]
Okay, no worries. Let us know when you're done and we'll start our test/review cycle.

**Comment by naesheim** [comment]
I have updated the commit now. 

I have tested it with:
name : [git repo, depth]
name : [git repo]
name : git repo

seems to work.

**Comment by al-jeyapal** [comment]
Merged and published as v1.2.0

**Pull request merged**
