### PR TITLE
WIP - Add 'branch' configuration option

### PR DESCRIPTION
**Pull request by praqma-thi**
Hey there,

I want to make the `--branch <branch>` option for `gitClone` available through the configuration.
I figured simply adding it to the configuration array (added with the `--depth <depth>` PR) would be awkward, so I went ahead and added support for Maps in the the configuration.

I feel the following would scale rather well in case more options get added.
```
project-bravo': [
    url: 'git@github.com:praqma-thi/project-bravo.git',
    depth: 1,
    branch: 'develop'
]
```

I'm also adding some functional tests using the `GradleRunner`, but they're more of a sketch, currently.
Notably, they rely on some dummy projects I set up on my GitHub account, I think it might make more sense to zip them up, add them as a test resouce and use local remotes, or at least make them on Bright Spark Labs' account.

All of this is still a work in progress, but I thought I'd make a PR early in case you have any comments.

### CODE REVIEW

**Comment by al-jeyapal** [comment]
Hi @praqma-thi,

I think we would prefer something like the following:

```
project-bravo': [
    url: 'git@github.com:praqma-thi/project-bravo.git',
    options: '--depth 1 --branch develop'
]
```

**Comment by praqma-thi** [comment]
Just a quick update, it wasn't too difficult to move it into that direction.
Bumped into an issue, though:

Calling `gitExec` with `--depth 1 --branch develop` as a parameter fails.
It runs `--depth` with `1 --branch develop` as its parameter.

The quick workaround was splitting the `options` value:
`if (repo.containsKey('options')) cmd.addAll(repo.options.split(' '))`
However, that will cause trouble when people add parameter values with spaces, wrapped in quotes.

Not sure yet how I'll deal with this yet, besides taking a String array in the options, or find a clever way of splitting the string so it preserves quote wraps. I'll think about it

On a brighter note, the functional tests are working and check if the shallow and branch-specific clones work. They're basic, but they're tests.

**Comment by al-jeyapal** [comment]
Thanks @praqma-thi. Yes perhaps use an array for clarity:

```
project-bravo': [
    url: 'git@github.com:praqma-thi/project-bravo.git',
    options: ['--depth', '1', '--branch', 'develop']
]
```

**Comment by praqma-thi** [comment]
Changed it to take the options as a String array.

Also tweaked the functional tests not to rely on my dummy repositories.
Right now the tests clone the project's own repository, but that can easily be changed.

**Comment by al-jeyapal** [comment]
Hi @praqma-thi just wanted to check whether you have finished on this branch? Can we begin our review/merge?

**Comment by praqma-thi** [comment]
Ah, yes. Feel free to go through the changes. Just let me know if something catches your eye.

**Review by al-jeyapal — APPROVED** [review]

**Pull request merged**
